[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest_env]
DYNAMODB_TABLE = "incc-shared-test"
AWS_ACCESS_KEY_ID = "testing"
AWS_SECRET_ACCESS_KEY = "testing"
AWS_SESSION_TOKEN = "testing"
AWS_DEFAULT_REGION = "sa-east-1"
